"""Chnged model

Revision ID: 16963c9fe5bf
Revises: d11ebd8c4f46
Create Date: 2024-08-22 10:42:05.914619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16963c9fe5bf'
down_revision = 'd11ebd8c4f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bond', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=50), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('bond', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
