"""Added the doctor column

Revision ID: 295caabc0f53
Revises: def88cf1b17f
Create Date: 2024-12-07 19:06:45.646779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '295caabc0f53'
down_revision = 'def88cf1b17f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctors')
    op.drop_table('appointments')
    op.drop_table('_alembic_tmp_bond')
    op.drop_table('doct')
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor', sa.String(length=50), nullable=False))

    with op.batch_alter_table('bond', schema=None) as batch_op:
        batch_op.alter_column('tags',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('bond', schema=None) as batch_op:
        batch_op.alter_column('tags',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('doctor')

    op.create_table('doct',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('qualifications', sa.VARCHAR(length=50), nullable=False),
    sa.Column('specialties', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('_alembic_tmp_bond',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('author', sa.VARCHAR(length=80), nullable=False),
    sa.Column('date_posted', sa.DATETIME(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=80), nullable=True),
    sa.Column('tags', sa.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), nullable=False),
    sa.Column('date', sa.VARCHAR(length=10), nullable=False),
    sa.Column('time', sa.VARCHAR(length=5), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('qualifications', sa.VARCHAR(length=50), nullable=False),
    sa.Column('specialties', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
